### ISSUE TITLE
Not receiving search results in qa.box.beckn.org for our BPP

### ISSUE THREAD

**Issue by siva-digiit** [Open-network-for-digital-commerce/ONDC-Live#5]
{"context":{"domain":"nic2004:52110","country":"IND","city":"std:080","action":"on_search","core_version":"0.9.1","bap_id":"box.beckn.org","bap_uri":"https://qa.api.box.beckn.org/bap/protocol/v1","transaction_id":"b776e5c5-020a-4b64-87b8-9df894cead18","message_id":"47be192f-3371-4a05-aa5a-8eb32abccbde","timestamp":"2022-03-24T06:23:19.212Z","bpp_uri":"https://bpp.dbp.ai","bpp_id":"bpp.dbp.ai","type":"BPP","ttl":120000}

**Comment by siva-digiit** [comment]
Tried again now. https://qa.box.beckn.org/ is not listing the products from our BPP. However, we receive the products through the gateway using our BAP https://bap.dbp.ai. Could you please check if the on_search from https://bpp.dbp.ai is being received by the BG?

{
    "context": {
        "domain": "nic2004:52110",
        "core_version": "0.9.3",
        "bap_id": "bap.dbp.ai",
        "bap_uri": "https://bap.dbp.ai",
        "type": "BPP",
        "city": "std:080",
        "country": "IND",
        "action": "on_search",
        "transaction_id": "655e05d1-2b7a-4692-b053-39645d237ad9",
        "message_id": "d9691965-206c-46f8-93ff-9e163768fa96",
        "timestamp": "2022-03-24T09:10:26.073Z",
        "ttl": 120000,
        "bpp_uri": "https://bpp.dbp.ai",
        "bpp_id": "bpp.dbp.ai"
    },
    "message": {
        "catalog": {
            "bpp/descriptor": {
                "name": "Digiit",
                "code": "Digiit",
                "short_desc": "Digiit Business Platform"
            },
            "bpp/categories": [
                {
                    "id": "635",
                    "descriptor": {
                        "name": "Grocery Items"
                    }
                }
            ],
            "bpp/fulfillments": [],
            "bpp/providers": [
                {
                    "id": "digiit-store",
                    "descriptor": {
                        "name": "Digiit Store",
                        "code": null,
                        "short_desc": null
                    },
                    "category_id": "635",
                    "categories": [
                        {
                            "id": "635",
                            "descriptor": {
                                "name": "Grocery Items"
                            }
                        }
                    ],
                    "items": [
                        {
                            "id": "7218#6609",
                            "descriptor": {
                                "name": "Sugar",
                                "short_desc": "Sugar",
                                "images": [
                                    "https://110digiistorage191.blob.core.windows.net/catalog/product/sugar.jpg"
                                ]
                            },
                            "price": {
                                "currency": "INR",
                                "value": 42,
                                "estimated_value": 42,
                                "computed_value": 42,
                                "listed_value": 42,
                                "offered_value": 42
                            },
                            "category_id": 635,
                            "rating": 5,
                            "location_id": "koramangala-4th-block-location",
                            "rateable": true,
                            "matched": true,
                            "related": true,
                            "recommended": true
                        }
                    ],
                    "exp": null,
                    "rateable": true
                }
            ],
            "exp": null
        }
    }
}

**Comment by siva-digiit** [comment]
@BLR-0118, not yet. We tried from our BAP and QA box. Have requested transaction logs from Dhiraj & Bhakti Rana to verify it further.

**Comment by dhiraj-nsdl** [comment]
@siva-digiit, Let us check and update you. Is transaction_id provided?

**Comment by siva-digiit** [comment]
@BLR-0118 , No. We still have issue with qa.box.beckn BAP (https://qa.api.box.beckn.org/bap/protocol/v1/). 
Reference: "transaction_id":"bdc46a57-07c4-4e5c-9b7f-3fde8e877080"
Bhakti Rana, reviewed the logs and informed that QA BOX BAP was not able to receive the request form BG.

**Comment by BLR-0118** [comment]
@siva-digiit - can you pls post screenshot from qa box if that's the problem

**Comment by siva-digiit** [comment]
@BLR-0118 , pls find the screen shots attached.

![image](https://user-images.githubusercontent.com/102281172/161206432-6a5151e4-7bdf-4604-b898-a793f1696b06.png)
![image](https://user-images.githubusercontent.com/102281172/161206459-079f47fa-2893-4890-9475-00f0877f3b40.png)
![image](https://user-images.githubusercontent.com/102281172/161206469-c8ce9e6e-3614-4ab2-abae-c4fe845ffc75.png)

**Comment by BLR-0118** [comment]
@siva-digiit - many fixes deployed for gateway & reference buyer app over last few days. Can you please check this once again & post screenshot here if not working?

**Comment by dhiraj-nsdl** [comment]
@siva-digiit We have deployed fix for 400 bad request issues. There is an issue at Buyer side where we have marked Nirmal and Rajat to look into it.

**Comment by siva-digiit** [comment]
@BLR-0118, Sure. Will check and update if we face any issue.

**Comment by siva-digiit** [comment]
@BLR-0118, I guess, you are referring to the below buyer side issue. FYR. This is what we get in qa box.
![image](https://user-images.githubusercontent.com/102281172/161412501-6441e7a3-7ad7-468b-aebb-c8f8a8e9318b.png)

**Comment by siva-digiit** [comment]
@BLR-0118, we still don't see the search results from our BPP in QA BOX. May I know, whom I can connect with from QA BOX team to verify this?

**Comment by dhiraj-nsdl** [comment]
@siva-digiit Are you passing Authorization header in your request?

**Comment by siva-digiit** [comment]
@BLR-0118 , Yes.

**Comment by siva-digiit** [comment]
@dhiraj-nsdl , does gateway validate the header or its not enabled?

**Comment by siva-digiit** [comment]
You may refer "transaction_id":"98cd6433-c126-4778-b9d4-e715d25788b1".

**Comment by dhiraj-nsdl** [comment]
@siva-digiit If you are not passing then it will not validate. But is a check at BAP end. I will ask Bhakti to co-ordinate with you.

**Comment by siva-digiit** [comment]
@dhiraj-nsdl, ok.

**Comment by siva-digiit** [comment]
@BLR-0118 , @dhiraj-nsdl , worked with Bhakti Rana and was able to address the header validation issue. Now, getting the acknowledgement for on_search from box.beckn.org. But, the results are not displayed in the client.

**Comment by dhiraj-nsdl** [comment]
@siva-digiit Let me ask Nirmal or Rajat to check this..

**Comment by BLR-0118** [comment]
@techframewirk - Hey Nirmal, pls help with this

**Comment by techframewirk** [comment]
I was not able to find any response in the logs when I searched with "lia" using the message_id of the triggered request. Can you please check the message_id and transaction_id of the request you are receiving and the response you are sending are matching?

**Comment by siva-digiit** [comment]
@techframewirk, will check and get back shortly.

**Comment by dhiraj-nsdl** [comment]
@techframewirk Hi Nirmal, I had msged you on slack with on_search request details..

**Comment by siva-digiit** [comment]
@techframewirk, getting the search results in qa box now. Had to fix an issue with the message_id.

**Comment by dhiraj-nsdl** [comment]
@techframewirk Awesome. Thanks Nirmal.

**Comment by siva-digiit** [comment]
Thanks all for the support. @BLR-0118, this issue is fixed now and the ticket can be closed.
